# Generated by Django 4.2 on 2023-05-23 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                ("file", models.FileField(upload_to="", verbose_name="Файл")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
            },
        ),
        migrations.CreateModel(
            name="FileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения пациента")),
                (
                    "patient_external_id",
                    models.CharField(
                        max_length=10, verbose_name="Внешний идентификатор пациента"
                    ),
                ),
                (
                    "diagnosis_code",
                    models.CharField(max_length=5, verbose_name="Код диагноза"),
                ),
                (
                    "diagnosis_name",
                    models.CharField(max_length=500, verbose_name="Название диагноза"),
                ),
                ("date_service", models.DateField(verbose_name="Дата оказания услуги")),
                (
                    "doctor_position",
                    models.CharField(max_length=500, verbose_name="Должность врача"),
                ),
                (
                    "doctor_external_id",
                    models.CharField(
                        max_length=10, verbose_name="Внешний идентификатор врача"
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(max_length=500, verbose_name="ФИО врача"),
                ),
                ("medical_appointments", models.TextField(verbose_name="Назначения")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.report",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные файла",
                "verbose_name_plural": "Данные файлов",
            },
        ),
    ]
