# Generated by Django 4.2 on 2023-05-26 22:28

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="service_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Код услуги"
            ),
        ),
        migrations.AlterField(
            model_name="filedata",
            name="doctor_external_id",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Внешний идентификатор врача"
            ),
        ),
        migrations.AlterField(
            model_name="filedata",
            name="doctor_name",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="ФИО врача"
            ),
        ),
        migrations.AlterField(
            model_name="filedata",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")],
                max_length=1,
                verbose_name="Пол пациента",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(
                upload_to=reports.models.update_filename, verbose_name="Файл"
            ),
        ),
    ]
