# Generated by Django 4.2 on 2023-05-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_filedata_service_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные анализа")),
                (
                    "file_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.filedata",
                        verbose_name="Данные файла",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.report",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные файла",
                "verbose_name_plural": "Данные файлов",
            },
        ),
    ]
