# Generated by Django 4.2 on 2023-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Данные анализа', 'verbose_name_plural': 'Данные анализа'},
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='service_code',
        ),
        migrations.AlterField(
            model_name='filedata',
            name='doctor_external_id',
            field=models.CharField(max_length=10, verbose_name='Внешний идентификатор врача'),
        ),
    ]
