# Generated by Django 4.2 on 2023-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="name",
            field=models.CharField(blank=True, max_length=500, verbose_name="Название"),
        ),
    ]
