# Generated by Django 4.2 on 2023-05-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_entities', '0002_alter_diagnosis_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Код диагноза'),
        ),
        migrations.AlterField(
            model_name='medicalappointments',
            name='synonyms',
            field=models.JSONField(default=list, verbose_name='Похожие выражения'),
        ),
    ]
