# Generated by Django 4.2 on 2023-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_entities', '0003_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointments',
            name='diagnoses',
            field=models.ManyToManyField(related_name='medical_appointments', to='medical_entities.diagnosis'),
        ),
    ]
